---
_hotel_id: HOL777
_portal_id: required-but-empty
_root_path: https://qa1.ttaws.com/rt
latitude: 40.8186
longitude: -73.93019
name: Holiday Inn Express-Bronx
email: sgontu@traveltripper.com
phone_number: 001-111-1111
address:
  street1: 500 Exterior Street
  street2: ''
  state: New York
  city: Bronx
  country: United States
  zip_code: '10451'
